### ISSUE TITLE
Gem not published to https://rubygems.org/

### ISSUE THREAD

**Issue by JeffAshton** [widarlein/logstash-input-mqtt#1]
Can you publish your Gem so I can test it out?

**Comment by JeffAshton** [comment]
Or my team is willing to take over the project if you want.

**Comment by widarlein** [comment]
Hi! I've not published the Gem since it is not properly documented. Right now I don't have so much time to work on this, so you are more than welcome to continue this if you are willing!

**Comment by ph** [comment]
Pretty cool guys! ping us on https://github.com/elasticsearch/logstash if you ever want to move it to the official logstash-plugins repositories.

**Comment by elvarb** [comment]
Getting full mqtt support would be fantastic, hope this goes forward

**Comment by natm** [comment]
Any chance of this being moved to the logstash-plugins repo?

**Comment by widarlein** [comment]
Sorry for not taking care of this, I'll look into it!
